### Base URL
@baseUrl = http://localhost:8787
@apiKey = ed58e6fd-8e18-4ee8-8b9c-4340bf3452e6

### Get Home
GET {{baseUrl}}/

### Get User Info
GET {{baseUrl}}/api/users/me
Content-Type: application/json
Authorization: Bearer {{apiKey}}

### Todos - List
GET {{baseUrl}}/api/todos
Authorization: Bearer {{apiKey}}

### Todos - Create
POST {{baseUrl}}/api/todos
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
	"title": "Belajar Hono"
}

### Todos - Update
PUT {{baseUrl}}/api/todos/1
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
	"title": "Belajar Hono - update"
}

### Todos - Toggle Check (soft-delete)
POST {{baseUrl}}/api/todos/3
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
	"check": true
}

### Todos - Delete all todo
DELETE {{baseUrl}}/api/todos
Content-Type: application/json
Authorization: Bearer {{apiKey}}

### Get Region Info
GET {{baseUrl}}/api/region?q=Kempek
Content-Type: application/json

### Get City Info
GET {{baseUrl}}/api/city?q=Cirebon
Content-Type: application/json
